# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=25w14craftmine
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=0.5.6-dev
maven_group=net.vulkanmod
archives_base_name=vulkanmod

# Dependencies
fabric_api_version=0.119.10+25w14craftmine
lwjgl_version=3.3.3
lwjgl_natives=natives-windows
findbugs_jsr305_version=3.0.2